### ISSUE TITLE
Alignment of image within canvas

### ISSUE THREAD

**Issue by saket** [tom5079/Minamo#20]
The default implementation of `Bound` places the image within the center of its available bounds. Could this be customized by providing it an `Alignment` parameter?

**Comment by tom5079** [comment]
`Bound` doesn't align the rect, `ScaleType` does.
See [ScaleType.kt](https://github.com/tom5079/SubSampledImage/blob/master/library/src/main/java/xyz/quaver/graphics/subsampledimage/ScaleType.kt).

**Comment by saket** [comment]
I see. Can it be used for achieving `FIT_WIDTH` while aligning the image to, say, the top? 

I'm effectively looking to find an alternative to this combination with `SubSampledImage`:

```kotlin
Image(
  contentScale = ContentScale.FillWidth,
  alignment = Alignment.TopCenter
)
```

**Comment by tom5079** [comment]
If you don't have to move the image around, `ScaleTypes.FIT_WIDTH` should be the solution.
Otherwise, you have to create your own Bound lambda that somehow pegs the image on top.

**Comment by tom5079** [comment]
Closed due to inactivity.
