### ISSUE TITLE
Zooming and panning multiple images together

### ISSUE THREAD

**Issue by AntsyLich** [tom5079/Minamo#24]
I am working on an manga reader app and using this library. The issue comes when i'm trying to make a double page reader. My code is like below:
```kt
Row(
    modifier = Modifier.fillMaxSize(),
    verticalAlignment = Alignment.CenterVertically,
) {
    images.fastForEach { image ->
       SubSampledImage(
          modifier = Modifier.weight(1f,
          imageSource = image.imageSource,
          state = rememberSubSampledImageState().apply {
              isGestureEnabled = true
          },
      )
    }
}
```

this gives me a output like below when i try zooming and panning

![Screenshot_1681410918](https://user-images.githubusercontent.com/59261191/231852976-0eb85fca-ce1a-4842-93d3-8f84b6d45d57.png)

Any way we can consider all the images in row a single image and apply zoom and panning to it.

**Comment by tom5079** [comment]
Zooming ang panning works by calling `state.setImageRect`.
There are a lot of different ways you can achieve this but see https://github.com/tom5079/SubSampledImage/blob/c7c202605b90de917bfc43d84ebb1853855b7b5c/library/src/main/java/xyz/quaver/graphics/subsampledimage/util.kt#L192 for reference.

**Comment by AntsyLich** [comment]
But aren't the images still stuck in their 50% of the screen.

Edit: I'll just pan the row

**Comment by tom5079** [comment]
yea it is out of scope for this library
